colon_ncdb <- read_stata('./data/NCDBColon_labeled.dta')

colon_ncdb <- colon_ncdb %>% mutate(
  RACE = as.numeric(RACE),
  SPANISH_HISPANIC_ORIGIN = as.numeric(SPANISH_HISPANIC_ORIGIN),
  INSURANCE_STATUS = as.numeric(INSURANCE_STATUS),
  UR_CD_13 = as.numeric(UR_CD_13),
  HISTOLOGY = as.numeric(HISTOLOGY),
  BEHAVIOR = as.numeric(BEHAVIOR),
  GRADE = as.numeric(GRADE),
  TUMOR_SIZE_SUMMARY = as.numeric(TUMOR_SIZE_SUMMARY),
  TUMOR_SIZE = as.numeric(TUMOR_SIZE),
  RX_HOSP_SURG_APPR_2010 = as.numeric(RX_HOSP_SURG_APPR_2010)
)

colon_ncdb <- colon_ncdb %>% mutate(
  facility_type = as.factor(FACILITY_TYPE_CD),
  facility_location = as.factor(FACILITY_LOCATION_CD),
  year_of_dx = as.factor(YEAR_OF_DIAGNOSIS),
  age = as.numeric(AGE),
  sex = as.factor(SEX),
  race = case_when(RACE == "1" ~ "white",
                   RACE == "2" ~ "black",
                   RACE == "3" ~ "american indian",
                   RACE %in% c("4", "5", "8", "96") ~ "east asian",
                   RACE %in% c("6", "10", "11", "12", "13", "14") ~ "southeast asian",
                   RACE %in% c("7", "20", "21", "22", "25", "26", "27", "28", "30", "31", "32", "97") ~ "pacific islander",
                   RACE %in% c("15", "16", "17") ~ "asian indian or pakistani",
                   RACE == "98" ~ "other",
                   TRUE ~ NA_character_),
  spanish_hispanic_origin = case_when(SPANISH_HISPANIC_ORIGIN == "0" ~ "non-spanish, non-hispanic",
                                      SPANISH_HISPANIC_ORIGIN == "1" ~ "mexican",
                                      SPANISH_HISPANIC_ORIGIN == "2" ~ "puerto rican",
                                      SPANISH_HISPANIC_ORIGIN == "3" ~ "cuban",
                                      SPANISH_HISPANIC_ORIGIN == "4" ~ "south or central american",
                                      SPANISH_HISPANIC_ORIGIN == "5" ~ "other specified spanish/hispanic origin",
                                      SPANISH_HISPANIC_ORIGIN == "6" ~ "spanish/hispanic/latino NOS",
                                      SPANISH_HISPANIC_ORIGIN == "7" ~ "spanish surname only",
                                      SPANISH_HISPANIC_ORIGIN == "8" ~ "dominican republic",
                                      TRUE ~ NA_character_),
  insurance_status = case_when(INSURANCE_STATUS == "0" ~ "not insured",
                               INSURANCE_STATUS == "1" ~ "private insurance/managed care",
                               INSURANCE_STATUS == "2" ~ "medicaid",
                               INSURANCE_STATUS == "3" ~ "medicare",
                               INSURANCE_STATUS == "4" ~ "other government",
                               TRUE ~ NA_character_),
  median_inc_quart = as.factor(MED_INC_QUAR_16),
  rurality = case_when(
    UR_CD_13 == "1" ~ "metro >= 1million",
    UR_CD_13 == "2" ~ "metro 250000-1million",
    UR_CD_13 == "3" ~ "metro <250000",
    UR_CD_13 == "4" ~ "urban >= 20000 adj metro",
    UR_CD_13 == "5" ~ "urban >= 20000 not adj metro",
    UR_CD_13 == "6" ~ "urban 2500-19999 adj metro",
    UR_CD_13 == "7" ~ "urban 2500-19999 not adj metro",
    UR_CD_13 == "8" ~ "rural adj metro",
    UR_CD_13 == "9" ~ "rural not adj metro",
  ),
  charlson_score = as.factor(CDCC_TOTAL_BEST),
  distance = as.numeric(CROWFLY),
  tumor_location = case_when(PRIMARY_SITE == "C180" ~ "cecum",
                             PRIMARY_SITE == "C181" ~ "appendix",
                             PRIMARY_SITE == "C182" ~ "ascending",
                             PRIMARY_SITE == "C183" ~ "hepatic",
                             PRIMARY_SITE == "C184" ~ "transverse",
                             PRIMARY_SITE == "C185" ~ "splenic",
                             PRIMARY_SITE == "C186" ~ "descending",
                             PRIMARY_SITE == "C187" ~ "sigmoid",
                             PRIMARY_SITE == "C188" ~ "overlapping",
                             PRIMARY_SITE == "C189" ~ "colon - not otherwise specified",
                             PRIMARY_SITE == "C260" ~ "intestine - ill specified"
  ),
  histology = case_when(HISTOLOGY == "8000" ~ "Neoplasm",
                        HISTOLOGY == "8001" ~ "Tumor cells",
                        HISTOLOGY == "8003" ~ "giant cell type",
                        HISTOLOGY == "8004" ~ "spindle cell type",
                        HISTOLOGY == "8005" ~ "clear cell type",
                        HISTOLOGY == "8010" ~ "carcinoma, NOS",
                        HISTOLOGY == "8012" ~ "large cell carcinoma",
                        HISTOLOGY == "8013" ~ "large cell neuroendocrine carcinoma",
                        HISTOLOGY == "8014" ~ "large cell carcinoma with rhabdoid phenotype",
                        HISTOLOGY == "8015" ~ "glassy cell carcinoma",
                        HISTOLOGY == "8020" ~ "undifferentied carcinoma",
                        HISTOLOGY == "8021" ~ "anaplastic carcinoma",
                        HISTOLOGY == "8022" ~ "pleomorphic carcinoma",
                        HISTOLOGY == "8030" ~ "giant cell and spindle cell carcinoma",
                        HISTOLOGY == "8031" ~ "giant cell carcinoma",
                        HISTOLOGY == "8032" ~ "spindle cell carcinoma",
                        HISTOLOGY == "8033" ~ "pseudosarcomatous carcinoma (sarcomatoid)",
                        HISTOLOGY == "8040" ~ "tumorlet",
                        HISTOLOGY == "8041" ~ "small cell carcinoma, NOS",
                        HISTOLOGY == "8043" ~ "small cell carcinoma, fusiform cell",
                        HISTOLOGY == "8044" ~ "small cell carcinoma, intermediate cell",
                        HISTOLOGY == "8045" ~ "combined small cell carcinoma",
                        HISTOLOGY == "8046" ~ "non-small cell carcinoma",
                        HISTOLOGY == "8050" ~ "papillary carcinoma",
                        HISTOLOGY == "8070" ~ "squamous cell carcinoma, NOS",
                        HISTOLOGY == "8071" ~ "squamous cell carcinoma keratinizing NOS",
                        HISTOLOGY == "8072" ~ "squamous cell carcinoma large cell, nonkeratinizing NOS",
                        HISTOLOGY == "8073" ~ "squamous cell carcinoma, small cell, nonkeratinizing",
                        HISTOLOGY == "8074" ~ "squamous cell carcinoma, spindle cell",
                        HISTOLOGY == "8075" ~ "squamous cell carcinoma, adenoid",
                        HISTOLOGY == "8077" ~ "squamous intraepithelial neoplasia",
                        HISTOLOGY == "8082" ~ "lymphoepithelial carcinoma",
                        HISTOLOGY == "8083" ~ "Basaloid squamous cell carcinoma",
                        HISTOLOGY == "8084" ~ "Squamous cell carcinoma, clear cell type",
                        HISTOLOGY == "8120" ~ "transitional cell carcinoma",
                        HISTOLOGY == "8123" ~ "basaloid carcinoma",
                        HISTOLOGY == "8124" ~ "Cloacogenic carcinoma",
                        HISTOLOGY == "8140" ~ "Adenocarcinoma, NOS",
                        HISTOLOGY == "8141" ~ "Scirrhous adenocarcinoma",
                        HISTOLOGY == "8142" ~ "Linitis plastica",
                        HISTOLOGY == "8143" ~ "Superficial spreading adenocarcinoma",
                        HISTOLOGY == "8144" ~ "Adenocarcinoma, intestinal type",
                        HISTOLOGY == "8145" ~ "Carcinoma, diffuse type",
                        HISTOLOGY == "8146" ~ "Monomorphic adenoma",
                        HISTOLOGY == "8147" ~ "Basal cell adenocarcinoma",
                        HISTOLOGY == "8148" ~ "gladular intraepithelial neoplasia",
                        HISTOLOGY == "8154" ~ "mixed pancreatic endocrine and exocrine tumor",
                        HISTOLOGY == "8161" ~ "bile duct cystadenocarcinoma",
                        HISTOLOGY == "8170" ~ "hepatocellular carcinoma",
                        HISTOLOGY == "8180" ~ "combined hepatocellular carcinoma and cholangio",
                        HISTOLOGY == "8190" ~ "trabecular adenocarcinoma",
                        HISTOLOGY == "8201" ~ "cribriform carcinoma",
                        HISTOLOGY == "8210" ~ "adenocarcinoma in polyp",
                        HISTOLOGY == "8211" ~ "Tubular adenocarcinoma",
                        HISTOLOGY == "8213" ~ "Serrated adenocarcinoma",
                        HISTOLOGY == "8220" ~ "adenocarcinoma in adenomatous polyposis coli",
                        HISTOLOGY == "8221" ~ "adenocarcinoma in multiple adenomatous polyp",
                        HISTOLOGY == "8230" ~ "solid carcinoma, NOS",
                        HISTOLOGY == "8231" ~ "Carcinoma simplex",
                        HISTOLOGY == "8240" ~ "carcinoid tumor",
                        HISTOLOGY == "8241" ~ "enterochromaffin cell carcinoid",
                        HISTOLOGY == "8242" ~ "enterochromaffin-like cell tumor",
                        HISTOLOGY == "8243" ~ "goblet cell carcinoid",
                        HISTOLOGY == "8244" ~ "Mixed adenoneuroendocrine carcinoma",
                        HISTOLOGY == "8245" ~ "Adenocarcinoid tumor",
                        HISTOLOGY == "8246" ~ "Neuroendocrine carcinoma, NOS",
                        HISTOLOGY == "8249" ~ "Atypical carcinoid tumor",
                        HISTOLOGY == "8255" ~ "Adenocarcinoma with mixed subtypes",
                        HISTOLOGY == "8260" ~ "Papillary adenocarcinoma, NOS",
                        HISTOLOGY == "8261" ~ "Adenocarcinoma in villous adenoma",
                        HISTOLOGY == "8262" ~ "villous adenocarcinoma",
                        HISTOLOGY == "8263" ~ "adenocarcinoma in tubulovillous adenoma",
                        HISTOLOGY == "8310" ~ "clear cell adenocarcinoma",
                        HISTOLOGY == "8320" ~ "granular cell carcinoma",
                        HISTOLOGY == "8323" ~ "mixed call adenocarcinoma",
                        HISTOLOGY == "8330" ~ "Follicular adenocarcinoma, NOS",
                        HISTOLOGY == "8341" ~ "Papillary microcarcinoma",
                        HISTOLOGY == "8345" ~ "Medullary carcinoma with amyloid stroma",
                        HISTOLOGY == "8380" ~ "Endometrioid adenocarcinoma, NOS",
                        HISTOLOGY == "8400" ~ "Sweat gland adenocarcinoma",
                        HISTOLOGY == "8420" ~ "Ceruminous adenocarcinoma",
                        HISTOLOGY == "8430" ~ "Mucoepidermoid carcinoma",
                        HISTOLOGY == "8440" ~ "Cystadenocarcinoma, NOS",
                        HISTOLOGY == "8441" ~ "Serous cystadenocarcinoma, NOS",
                        HISTOLOGY == "8460" ~ "Papillary serous cystadenocarcinoma",
                        HISTOLOGY == "8461" ~ "Serous surface papillary carcinoma",
                        HISTOLOGY == "8470" ~ "Mucinous cystadenoma, NOS",
                        HISTOLOGY == "8471" ~ "Papillary mucinous cystadenocarcinoma",
                        HISTOLOGY == "8472" ~ "mucinous cystic tumor of borderline malignancy",
                        HISTOLOGY == "8480" ~ "mucinous adenocarcinoma",
                        HISTOLOGY == "8481" ~ "Mucin-producing adenocarcinoma",
                        HISTOLOGY == "8482" ~ "Mucinous adenocarcinoma endocervical type",
                        HISTOLOGY == "8490" ~ "Signet ring cell carcinoma",
                        HISTOLOGY == "8500" ~ "Intraductal carcinoma",
                        HISTOLOGY == "8507" ~ "Intraductal micropapillary carcinoma",
                        HISTOLOGY == "8510" ~ "Medullary carcinoma, NOS",
                        HISTOLOGY == "8512" ~ "Medullary carcinoma with lymphoid stroma",
                        HISTOLOGY == "8513" ~ "Atypical medullary carcinoma",
                        HISTOLOGY == "8523" ~ "Infiltrating duct mixed with other types of carcinoma",
                        HISTOLOGY == "8542" ~ "Paget disease, extramammary",
                        HISTOLOGY == "8550" ~ "Acinar cell carcinoma",
                        HISTOLOGY == "8560" ~ "Adenosquamous carcinoma",
                        HISTOLOGY == "8570" ~ "Adenocarcinoma with squamous metaplasia",
                        HISTOLOGY == "8571" ~ "Adenocarcinoma with cartilaginous and osseous metaplasia",
                        HISTOLOGY == "8572" ~ "Adenocarcinoma with spindle cell metaplasia",
                        HISTOLOGY == "8573" ~ "Adenocarcinoma with apocrine metaplasia",
                        HISTOLOGY == "8574" ~ "Adenocarcinoma with neuroendocrine differentiation",
                        HISTOLOGY == "8575" ~ "Metaplastic carcinoma, NOS",
                        HISTOLOGY == "8576" ~ "Hepatoid adenocarcinoma",
                        HISTOLOGY == "8680" ~ "Paraganglioma, malignant",
                        HISTOLOGY == "8711" ~ "Glomus tumor, malignant",
                        HISTOLOGY == "8720" ~ "Malignant melanoma, NOS",
                        HISTOLOGY == "8730" ~ "Amelanotic melanoma",
                        HISTOLOGY == "8800" ~ "Sarcoma, NOS",
                        HISTOLOGY == "8801" ~ "Spindle cell sarcoma",
                        HISTOLOGY == "8802" ~ "Giant cell sarcoma",
                        HISTOLOGY == "8803" ~ "Small cell sarcoma",
                        HISTOLOGY == "8804" ~ "Epithelioid sarcoma",
                        HISTOLOGY == "8805" ~ "Undifferentiated sarcoma",
                        HISTOLOGY == "8806" ~ "Desmoplastic small round cell tumor",
                        HISTOLOGY == "8810" ~ "Fibrosarcoma, NOS",
                        HISTOLOGY == "8811" ~ "Fibromyxosarcoma",
                        HISTOLOGY == "8815" ~ "Solitary fibrous tumor, malignant",
                        HISTOLOGY == "8825" ~ "Myofibroblastic tumor, NOS",
                        HISTOLOGY == "8830" ~ "Malignant fibrous histiocytoma",
                        HISTOLOGY == "8850" ~ "Liposarcoma, NOS",
                        HISTOLOGY == "8851" ~ "Liposarcoma, well differentiated",
                        HISTOLOGY == "8852" ~ "Myxoid liposarcoma",
                        HISTOLOGY == "8858" ~ "Dedifferentiated liposarcoma",
                        HISTOLOGY == "8890" ~ "Leiomyosarcoma, NOS",
                        HISTOLOGY == "8895" ~ "Myosarcoma",
                        HISTOLOGY == "8896" ~ "Myxoid leiomyosarcoma",
                        HISTOLOGY == "8900" ~ "Rhabdomyosarcoma, NOS",
                        HISTOLOGY == "8930" ~ "Endometrial stromal sarcoma",
                        HISTOLOGY == "8931" ~ "Endometrial stromal sarcoma, low grade",
                        HISTOLOGY == "8933" ~ "Adenosarcoma",
                        HISTOLOGY == "8935" ~ "Stromal sarcoma, NOS",
                        HISTOLOGY == "8936" ~ "Gastrointestinal stromal sarcoma",
                        HISTOLOGY == "8940" ~ "Mixed tumor, malignant, NOS",
                        HISTOLOGY == "8950" ~ "Mullerian mixed tumor",
                        HISTOLOGY == "8963" ~ "Malignant rhabdoid tumor",
                        HISTOLOGY == "8980" ~ "Carcinosarcoma, NOS",
                        HISTOLOGY == "8982" ~ "Malignant myoepithelioma",
                        HISTOLOGY == "9015" ~ "Mucinous adenocarcinofibroma",
                        HISTOLOGY == "9041" ~ "Synovial sarcoma, spindle cell",
                        HISTOLOGY == "9043" ~ "Synovial sarcoma, biphasic",
                        HISTOLOGY == "9044" ~ "Clear cell sarcoma, NOS",
                        HISTOLOGY == "9060" ~ "Dysgerminoma",
                        HISTOLOGY == "9064" ~ "Germinoma",
                        HISTOLOGY == "9071" ~ "Yolk sac tumor",
                        HISTOLOGY == "9085" ~ "Mixed germ cell tumor",
                        HISTOLOGY == "9100" ~ "Choriocarcinoma, NOS",
                        HISTOLOGY == "9110" ~ "Mesonephroma, malignant",
                        HISTOLOGY == "9120" ~ "Hemangiosarcoma",
                        HISTOLOGY == "9133" ~ "Epithelioid hemangioendothelioma/malignant",
                        HISTOLOGY == "9170" ~ "Lymphangiosarcoma",
                        HISTOLOGY == "9243" ~ "Dedifferentiated chondrosarcoma",
                        HISTOLOGY == "9260" ~ "Ewing sarcoma",
                        HISTOLOGY == "9364" ~ "Peripheral neuroectodermal tumor",
                        HISTOLOGY == "9473" ~ "Primitive neuroectodermal tumor, NOS",
                        HISTOLOGY == "9500" ~ "Neuroblastoma, NOS",
                        HISTOLOGY == "9540" ~ "Malignant peripheral nerve sheath tumor",
                        HISTOLOGY == "9571" ~ "Perineurioma, malignant",
                        HISTOLOGY == "9580" ~ "Granular cell tumor, malignant",
                        HISTOLOGY == "9581" ~ "Alveolar soft part sarcoma"
  ),
  adenocarcinoma = case_when(HISTOLOGY %in% c("8140",
                                              "8141",
                                              "8142",
                                              "8143",
                                              "8144",
                                              "8145",
                                              "8146",
                                              "8147",
                                              "8148",
                                              "8154",
                                              "8161",
                                              "8170",
                                              "8180",
                                              "8190",
                                              "8201",
                                              "8210",
                                              "8211",
                                              "8213",
                                              "8220",
                                              "8221",
                                              "8230",
                                              "8231",
                                              "8240",
                                              "8241",
                                              "8242",
                                              "8243",
                                              "8244",
                                              "8245",
                                              "8246",
                                              "8249",
                                              "8255",
                                              "8260",
                                              "8261",
                                              "8262",
                                              "8263",
                                              "8310",
                                              "8320",
                                              "8323",
                                              "8330",
                                              "8341",
                                              "8345",
                                              "8380") ~ 1,
                             TRUE ~ 0),
  behaviour = case_when(
    BEHAVIOR == "2" ~ "in-situ",
    BEHAVIOR == "3" ~ "invasive"
  ),
  grade = case_when(
    GRADE == "1" ~ "well differentiated",
    GRADE == "2" ~ "moderately differentiated",
    GRADE == "3" ~ "poorly differentiated",
    GRADE == "4" ~ "undifferentiated",
    GRADE == "9" ~ "in-situ/cell type not determined/not stated/unknown primary"
  ),
  clinical_T = case_when(
    TNM_CLIN_T == "c0" ~ "T0",
    TNM_CLIN_T %in% c("c1", "c1A", "c1B") ~ "T1",
    TNM_CLIN_T %in% c("c2") ~ "T2",
    TNM_CLIN_T %in% c("c3") ~ "T3",
    TNM_CLIN_T %in% c("c4", "c4A", "c4B") ~ "T4",
    TNM_CLIN_T %in% c("pIS") ~ "Tis"
  ),
  clinical_N = case_when(
    TNM_CLIN_N == "c0" ~ "N0",
    TNM_CLIN_N %in% c("c1", "c1A", "c1B") ~ "N1",
    TNM_CLIN_N %in% c("c2", "c2A", "c2B") ~ "N2"
  ),
  clinical_M = case_when(
    TNM_CLIN_M == "c0" ~ "M0",
    TNM_CLIN_M %in% c("c1", "c1A", "c1B") ~ "M1"
  ),
  tumor_size = case_when(year_of_dx == "2016" & 
                           TUMOR_SIZE_SUMMARY != "999" ~ TUMOR_SIZE_SUMMARY,
                         year_of_dx != "2016" &
                           TUMOR_SIZE != "999" ~ TUMOR_SIZE),
  pre_referral_trt = CLASS_OF_CASE,
  days_from_dx_to_first_surg = DX_SURG_STARTED_DAYS,
  days_from_dx_to_def_surg = DX_DEFSURG_STARTED_DAYS,
  def_surg_procedure = case_when(RX_SUMM_SURG_PRIM_SITE == "0" ~ "no surg",
                                 RX_SUMM_SURG_PRIM_SITE %in% c("10", "11", "12", "13", "14")  ~ "local tumor destruction",
                                 RX_SUMM_SURG_PRIM_SITE %in% c("20", "21", "22", "23", "24", "25", 
                                                               "26", "27", "28", "29") ~ "local tumor excision",
                                 RX_SUMM_SURG_PRIM_SITE == "30" ~ "segmental colectomy",
                                 RX_SUMM_SURG_PRIM_SITE == "32" ~ "segmental colectomy plus resection of contiguous organ",
                                 RX_SUMM_SURG_PRIM_SITE == "40" ~ "subtotal/hemicolectomy",
                                 RX_SUMM_SURG_PRIM_SITE == "41" ~ "subtotal/hemicolectomy plus resection of contiguous organ",
                                 RX_SUMM_SURG_PRIM_SITE == "50" ~ "total colectomy",
                                 RX_SUMM_SURG_PRIM_SITE == "51" ~ "total colectomy plus resection of contiguous organ",
                                 RX_SUMM_SURG_PRIM_SITE == "60" ~ "total proctocolectomy",
                                 RX_SUMM_SURG_PRIM_SITE == "61" ~ "total proctocolectomy plus resection of contiguous organ",
                                 RX_SUMM_SURG_PRIM_SITE == "70" ~ "colectomy or proctocolectomy plus resection of contiguous organ NOS",
                                 RX_SUMM_SURG_PRIM_SITE == "80" ~ "colectomy NOS",
                                 RX_SUMM_SURG_PRIM_SITE == "90" ~ "surgery, NOS",
                                 RX_SUMM_SURG_PRIM_SITE == "99" ~ "unknown"
  ),
  neoadj_chemo = case_when(DX_DEFSURG_STARTED_DAYS - DX_CHEMO_STARTED_DAYS > 0 ~ 'yes',
                           TRUE ~ 'no'),
  neoadj_rad = case_when(DX_DEFSURG_STARTED_DAYS - DX_RAD_STARTED_DAYS > 0 ~ 'yes',
                         TRUE ~ 'no'),
  surg_approach = case_when(RX_HOSP_SURG_APPR_2010 %in% c("3", "4") ~ "lap",
                            RX_HOSP_SURG_APPR_2010 == "5" ~ "open",
                            RX_HOSP_SURG_APPR_2010 %in% c("1", "2") ~ "robotic"),
  death_30 = PUF_30_DAY_MORT_CD,
  death_90 = PUF_90_DAY_MORT_CD,
)

colon_ncdb <- colon_ncdb %>% dplyr::select(facility_type,
                          facility_location,
                          distance,
                          year_of_dx,
                          age,
                          sex, 
                          race, 
                          spanish_hispanic_origin,
                          insurance_status,
                          median_inc_quart,
                          rurality,
                          charlson_score,
                          tumor_location,
                          adenocarcinoma,
                          behaviour,
                          grade,
                          clinical_T,
                          clinical_N,
                          clinical_M,
                          tumor_size,
                          pre_referral_trt,
                          days_from_dx_to_def_surg,
                          def_surg_procedure,
                          neoadj_chemo,
                          neoadj_rad,
                          surg_approach,
                          death_30,
                          death_90) %>%
  mutate(
    facility_type = as.factor(facility_type),
    facility_location = as.factor(facility_location),
    distance = as.numeric(distance),
    year_of_dx = as.factor(year_of_dx),
    age = as.numeric(age),
    sex = as.factor(sex),
    race = as.factor(race),
    spanish_hispanic_origin = as.factor(spanish_hispanic_origin),
    insurance_status = as.factor(insurance_status),
    median_inc_quart = as.factor(median_inc_quart),
    rurality = as.factor(rurality),
    charlson_score = as.factor(charlson_score),
    tumor_location = as.factor(tumor_location),
    adenocarcinoma = as.factor(adenocarcinoma),
    behaviour = as.factor(behaviour),
    grade = as.factor(grade),
    clinical_T = as.factor(clinical_T),
    clinical_N = as.factor(clinical_N),
    clinical_M = as.factor(clinical_M),
    tumor_size = as.numeric(tumor_size),
    pre_referral_trt = as.factor(pre_referral_trt),
    days_from_dx_to_def_surg = as.numeric(days_from_dx_to_def_surg),
    def_surg_procedure = as.factor(def_surg_procedure),
    neoadj_chemo = as.factor(neoadj_chemo),
    neoadj_rad = as.factor(neoadj_rad),
    surg_approach = as.factor(surg_approach),
    death_30 = as.factor(death_30),
    death_90 = as.factor(death_90)
  )

colon_ncdb <- colon_ncdb %>% filter(age >= 18 & age <= 85 & 
                            days_from_dx_to_def_surg > 0 & days_from_dx_to_def_surg < 365 &
                            clinical_M == "M0" &
                            adenocarcinoma == 1 & 
                            def_surg_procedure %in% c("segmental colectomy",
                                                      "segmental colectomy plus resection of contiguous organ",
                                                      "subtotal/hemicolectomy",
                                                      "subtotal/hemicolectomy plus resection of contiguous organ",
                                                      "total colectomy",
                                                      "total colectomy plus resection of contiguous organ",
                                                      "total proctocolectomy",
                                                      "total proctocolectomy plus resection of contiguous organ",
                                                      "colectomy or proctocolectomy plus resection of contiguous organ NOS",
                                                      "colectomy NOS",
                                                      "surgery, NOS") &
                            surg_approach != "robotic" &
                            death_90 != "9" &
                            is.na(facility_type) == F &
                            is.na(facility_location) == F &
                            is.na(distance) == F &
                            is.na(age) == F &
                            is.na(sex) == F &
                            is.na(race) == F &
                            is.na(spanish_hispanic_origin) == F &
                            is.na(insurance_status) == F &
                            is.na(median_inc_quart) == F &
                            is.na(charlson_score) == F &
                            is.na(tumor_location) == F &
                            is.na(behaviour) == F &
                            is.na(grade) == F &
                            is.na(clinical_T) == F &
                            is.na(clinical_N) == F &
                            is.na(tumor_size) == F &
                            is.na(days_from_dx_to_def_surg) == F & 
                            is.na(def_surg_procedure) == F) %>% 
  mutate(
    death_90 = case_when(death_90 == "1" ~ 1, death_90 == "0" ~ 0)
  )

colon_ncdb <- drop.levels(colon_ncdb, reorder=T) %>% dplyr::select(-c(death_90, clinical_M, adenocarcinoma, year_of_dx))

colon_ncdb <- dummy_cols(colon_ncdb, remove_first_dummy=T, remove_selected_columns=T) 

names(colon_ncdb) <- make.names(names(colon_ncdb))